blog_on_rails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # get "/posts/new" => "posts#new", as: :new_post
  # post "/posts" => "posts#create", as: :posts

  # get "/posts/:id" => "posts#show", as: :post

  # # get "/post" => "posts#index", as: :root
  # get "/" => "posts#index", as: :root

  # get "/posts/:id/edit" => "posts#edit", as: :edit_post

  # patch "/posts/:id" => "posts#update"

  # delete "/posts/:id" => "posts#destroy"

  root to: redirect(path: "/posts")

  resources :posts do
    resources :comments, only: [:create, :destroy], shallow: true
  end

  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]
end

blog_on_rails/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end

    #can :edit, Idea, user_id: user.id
    alias_action :create, :read, :update, :destroy, to: :crud

    can :crud, Post, user_id: user.id

    can :crud, Comment do |comment|
      comment.user == user || comment.post.user == user
    end

    if user.is_admin?
      can :manage, :all
    end
  
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

blog_on_rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog_on_rails/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
end

blog_on_rails/app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    belongs_to :user

    validates :title, presence: true
    validates :body, presence: true
end

blog_on_rails/app/models/user.rb
class User < ApplicationRecord
    has_many :posts, dependent: :nullify
    has_many :comments, dependent: :nullify
    has_secure_password

    validates(
        :email,
        presence: true,
        uniqueness: true,
        format: URI::MailTo::EMAIL_REGEXP,
    )
end

blog_on_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private

    def current_user
        if session[:user_id].present?
            @current_user ||= User.find session[:user_id]
        end
    end
    helper_method :current_user

    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?

    def authenticate_user!
        unless user_signed_in?
            flash[:danger] = "You Must Sign In First"
            redirect_to new_session_path
        end
    end
end

blog_on_rails/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find params[:post_id]
        @comment = Comment.new comment_params
        @comment.post = @post
        @comment.user = current_user
        if @comment.save
            redirect_to post_path(@post)
        else
            render :show
        end
    end

    def destroy
        @comment = Comment.find params[:id]
        @comment.destroy
        redirect_to post_path(@comment.post)
    end

    private

    def comment_params
        params.require(:comment).permit(:body)
    end
end

blog_on_rails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:show, :index]
    before_action :find_post, only: [:show, :edit, :update, :destroy]
    before_action :authorize, only: [:edit, :update, :delete]

    def new
        @post = Post.new
    end

    def create
        @post = Post.new post_params
        @post.user = current_user
        if @post.save
            flash[:primary] = "Post created!"
            redirect_to post_path(@post.id)
        else
            render :new
        end
    end
    
    def show
        @comment = Comment.new

        @comments = @post.comments.order(created_at: :desc)
    end

    def index
        @posts = Post.all.order(created_at: :desc)
    end

    def edit
        unless can?(:edit, @post)
            flash[:danger]
            redirect_to root_path
        end
    end

    def update
        if @post.update post_params
            flash[:dark] = "Post has been updated!"
            redirect_to post_path(@post)
        else
            render :edit
        end
    end

    def destroy
        @post.destroy
        flash[:danger] = "Post has been deleted!"
        redirect_to posts_path
    end

    private

    def post_params
        params.require(:post).permit(:title, :body)
    end

    def find_post
        @post = Post.find params[:id]
    end

    def authorize
        unless can?(:crud, @idea)
            flash[:danger] = "Not Authorized"
            redirect_to root_path
        end
    end
end

blog_on_rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by_email params[:email]

        if user&.authenticate(params[:password])
            session[:user_id] = user.id
            flash[:primary] = "Welcome, #{user.name}"
            redirect_to root_path
        else
            flash[:danger] = "Wrong email or password"
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:primary] = "Signed Out"
        redirect_to root_path
    end
end

blog_on_rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new user_params
        if @user.save
            session[:user_id] = @user.id
            redirect_to posts_path
        else
            render :new
        end
    end

    private
    
    def user_params
        params.require(:user).permit(
            :name,
            :email,
            :password,
            :password_confirmation,
        )
    end
end

blog_on_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

blog_on_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Blog On Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true%>
<%= javascript_include_tag 'manifest', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-blue bg-light">
      <div class="container-fluid">
          <a class="navbar-brand " href="/">Blog On Rails</a>
          <div class="form-inline my-2 my-lg-0" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li>
                <a class="nav-link mr-3" href="/posts/new">New Post</a>
              </li>
              <% if user_signed_in? %>
                <li class="nav-link mr-3 text-primary">
                  Hello <%= current_user.name %>
                </li>
                <li class="nav-link mr-3">
                  <%= link_to "Sign Out", session_path, method: :delete, data: {confirm: "Log Out?"} %>
                </li>
              <% else %>
              <li class="nav-item mr-3">
                <a class="nav-link btn text-primary" href="/session/new">Sign In</a>
              </li>
              <li class="nav-item mr-3">
                <a class="nav-link btn text-primary" href="/users/new">Sign Up</a>
              </li>
              <% end %>
            </ul>
            <hr>
          </div>
        </div>
      </nav>
      <% flash.each do |type, message| %>
      <div class="container">
      <span class="alert alert-<%= type %>" role="alert"><%= message %></span>
      <% end %>
      </div>
  <%= yield %>
  </body>
</html>

blog_on_rails/app/views/posts/edit.html.erb
<% if @post.errors.any? %>
    <ul>
        <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<div class="container">
<%= form_for @post do |f| %>
    <div class="form-group" style="padding-top: 10px;">
        <%= f.label :title, class: "control-label" %>
        <div class="col-md-3">
            <%= f.text_field :title, class: "form-control" %>
        </div>
    </div>
    <div class="form-group" style="padding-top: 10px;">
        <%= f.label :body, class: "control-label" %>
        <div class="col-md-3">
            <%= f.text_area :body, class: "form-control" %>
        </div>
    </div>
    <div style="padding-top: 10px;">
        <%= f.submit "Update Post", class: "btn btn-outline-primary" %>
    </div>
<% end %>
</div>

blog_on_rails/app/views/posts/index.html.erb
<div class="row row-cols-1 row-cols-md-3 g-4" style="padding: 20px">
<% @posts.each do |post| %>
    <div class="col">
        <div class="card h-100">
            <div class="card-body">
                <a class="card-title" href="/posts/<%= post.id %>"><%= post.title %></a>
                <p class="card-text"><%= post.body %></p>       
            </div>
        </div>
    </div>
<% end %>
</div>

blog_on_rails/app/views/posts/new.html.erb
<% if @post.errors.any? %>
    <ul>
        <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>
<div class="container">
<%= form_for @post do |f| %>
    <div class="form-group" style="padding-top: 10px;">
        <%= f.label :title, class: "control-label" %>
        <div class="col-md-3">
            <%= f.text_field :title, class: "form-control" %>
        </div>
    </div>
    <div class="form-group" style="padding-top: 10px;">
        <%= f.label :body, class: "control-label" %>
        <div class="col-md-3">
            <%= f.text_area :body, class: "form-control" %>
        </div>
    </div>
    <div style="padding-top: 10px;">
        <%= f.submit "Create Post", class: "btn btn-outline-primary" %>
    </div>
<% end %>
</div>

blog_on_rails/app/views/posts/show.html.erb
<div class="container" style="padding: 20px;">
    <div class="card border-0">
        <div class="card-body">
            <h3 class="card-title"><%= @post.title %></h3>
            <p class="card-text"><%= @post.body %></p>
            <p class="card-text text-muted" style="font-size: small;">Posted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user&.name || "[Deleted]" %></p>
                        <% if can?(:crud, @idea) %>
            <div class="form-inline">
                <div class="btn btn-outline-primary">
                <%= link_to "Edit", edit_post_path(@post) %>
                </div>
                <div class="btn btn-outline-primary">
                <%= link_to "Delete", @post, method: :delete, data: {confirm: "Are you sure?"} %>
                </div>
                <% end %>
            </div>
        </div>

        <div class="card-body">
            <h5 class="card-title">Comment</h5>
            <div>
            <%= form_with model: [@post, @comment], local: true do |form| %>
                <%= form.text_area(:body, cols: 50, rows: 5, placeholder: "What's on your mind?") %>
            <div>
                <%= form.submit "Submit",  class: "btn btn-outline-primary" %>
            </div>    
            <% end %>
            </div>

            <div class="container">
            <ul>
                <% @comments.each do |comment| %>
                <li style="list-style-type: none; padding-top: 20px;">
                    <p class="card-text" style="margin: 0;">
                        <%= comment.body %>
                    </p>
                    <p class="card-text text-muted" style="font-size: small;">
                        Commented <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.user&.name || "[DELETED]" %> 
                        <% if can?(:crud, comment) %>
                            &#8226; <%= link_to "Delete", comment_path(comment), method: :delete, data: { confirm: "Are you sure?"} %>
                        <% end %>
                    </p>
                </li>
                <% end %>
            </ul>
            </div>
        </div>
    </div>
</div>

blog_on_rails/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_with model: @user, local: true do |form| %>
    <% if @user.errors.present? %>
        <%= @user.errors.full_messages.join(", ") %>
    <% end %>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>
    <div>
        <%= form.label :email %>
        <%= form.email_field :email %>
    </div>
    <div>
        <%= form.label :password %>
        <%= form.password_field :password %>
    </div>
    <div>
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation %>
    </div>
    <%= form.submit "Sign Up" %>
<% end %>